version: '3.1'

services:

  workspace:
    build:
      context: ./docker
    volumes:
      - ./:/var/etikbnb-api
    working_dir: /var/etikbnb-api
    entrypoint: /var/etikbnb-api/entrypoint.sh
    networks:
      - etikbnb-db_default
    ports:
      - 8000:8000
      - 443:443
      - 444:444

networks:
  etikbnb-db_default:
    external: true